name: Weekly Notifier (Discord)

on:
  schedule:
    # Run every Sunday at multiple minutes to tolerate DST shifts; script gates at local 18:00 America/Santiago
    - cron: '0 20 * * 0' # ~17:00-18:00 local depending on DST; script will gate
    - cron: '5 20 * * 0'
    - cron: '10 20 * * 0'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run notifier (no deps)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node scripts/notify-discord.mjs
